version: '3'
networks:
  net:
    driver: bridge
  test-net:
    driver: bridge

services:
  rds-practice:
    image: dancingfish/rds-practice:rds-practice
    container_name: rds-practice
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
      - test-db
      - flyway
    environment:
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.datasource.url: jdbc:mysql://db:3306/rdsdb
      spring.datasource.username: root
      spring.datasource.password: 123
    networks:
      - net
      - test-net

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: rdsdb
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - net

  test-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test-rdsdb
    ports:
      - 3307:3306
    volumes:
      - test-db-data:/var/lib/mysql
    networks:
      - test-net

  test-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - test-db
    ports:
      - "8001:80"
    networks:
      - test-net
    environment:
      PMA_HOST: test-db
      PMA_PORT: 3306

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=rdsdb -user=root -password=123 -connectRetries=60 migrate
    volumes:
      - ./schema.sql:/flyway/sql/V1__Initial.sql
    depends_on:
      - db
    networks:
      - net


volumes:
  db-data:
  test-db-data:
